name: Ideia
description: Sugira um recurso ou melhoria
labels: [ideia]
body:
  - type: textarea
    id: problem
    attributes:
      label: Qual problema isso resolve
      description: Conte a situação em que você sentiu falta disso.
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Como você imagina
    validations:
      required: true
